# Generated by Django 5.1.15 on 2026-07-07 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("guests", "0001_initial"),
        ("reservations", "0002_reservationroomline_room"),
        ("rooms", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Stay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_house", "In house"),
                            ("checked_out", "Checked out"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="in_house",
                        max_length=16,
                    ),
                ),
                ("planned_check_in_date", models.DateField()),
                ("planned_check_out_date", models.DateField()),
                ("actual_check_in_at", models.DateTimeField()),
                ("actual_check_out_at", models.DateTimeField(blank=True, null=True)),
                (
                    "check_in_notes",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "check_out_notes",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "checkout_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stays_checked_in",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "checked_out_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stays_checked_out",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stays",
                        to="tenancy.hotel",
                    ),
                ),
                (
                    "primary_guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_stays",
                        to="guests.guest",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stays",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "reservation_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stays",
                        to="reservations.reservationroomline",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stays",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "db_table": "stays",
                "ordering": ["-actual_check_in_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StayGuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("primary", "Primary"), ("companion", "Companion")],
                        default="companion",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stay_links",
                        to="guests.guest",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stay_guests",
                        to="tenancy.hotel",
                    ),
                ),
                (
                    "stay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="stays.stay",
                    ),
                ),
            ],
            options={
                "db_table": "stay_guests",
                "ordering": ["stay_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="StayStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("in_house", "In house"),
                            ("checked_out", "Checked out"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("in_house", "In house"),
                            ("checked_out", "Checked out"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stay_status_log_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stay_status_logs",
                        to="tenancy.hotel",
                    ),
                ),
                (
                    "stay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="stays.stay",
                    ),
                ),
            ],
            options={
                "db_table": "stay_status_logs",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="stay",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "in_house")),
                fields=("room",),
                name="unique_in_house_stay_per_room",
            ),
        ),
        migrations.AddConstraint(
            model_name="stayguest",
            constraint=models.UniqueConstraint(
                fields=("stay", "guest"), name="unique_guest_per_stay"
            ),
        ),
        migrations.AddConstraint(
            model_name="stayguest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "primary")),
                fields=("stay",),
                name="unique_primary_guest_per_stay",
            ),
        ),
    ]
