# Generated by Django 5.1.15 on 2026-07-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='nightly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
