# Generated by Django 5.1.15 on 2026-07-15 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0003_backfill_nightly_rate'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StayRatePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('nightly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('source', models.CharField(choices=[('booking', 'Booking'), ('extension', 'Extension'), ('override', 'Override'), ('legacy_remediation', 'Legacy remediation')], max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('override_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stay_rate_periods_approved', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_rate_periods', to='tenancy.hotel')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_periods', to='stays.stay')),
            ],
            options={
                'db_table': 'stay_rate_periods',
                'ordering': ['stay_id', 'start_date', 'id'],
                'indexes': [models.Index(fields=['stay', 'start_date'], name='stay_rate_p_stay_id_8d0670_idx')],
                'constraints': [models.UniqueConstraint(fields=('stay', 'start_date'), name='uniq_stay_rate_period_start'), models.CheckConstraint(check=models.Q(start_date__lt=models.F('end_date')), name='stay_rate_period_start_before_end'), models.CheckConstraint(check=models.Q(('nightly_rate__isnull', True), ('nightly_rate__gt', 0), _connector='OR'), name='stay_rate_period_rate_positive_or_null'), models.CheckConstraint(check=models.Q(('nightly_rate__isnull', True), models.Q(('currency', ''), _negated=True), _connector='OR'), name='stay_rate_period_priced_has_currency')],
            },
        ),
    ]
