# Generated by Django 5.1.15 on 2026-07-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservationroomline_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_channel_name',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='reservation',
            name='booking_kind',
            field=models.CharField(choices=[('instant', 'Instant'), ('future', 'Future')], default='instant', max_length=16),
        ),
        migrations.AddField(
            model_name='reservation',
            name='expected_arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='expected_payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank transfer'), ('other', 'Other')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='reservation',
            name='no_show_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='primary_guest_document_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='reservation',
            name='primary_guest_document_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='reservation',
            name='primary_guest_nationality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
