# Generated by Django 5.1.15 on 2026-07-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_booking_channel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='public_cancel_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='public_cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='public_manage_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='public_manage_token_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='source',
            field=models.CharField(choices=[('direct', 'Direct'), ('phone', 'Phone'), ('walk_in', 'Walk-in'), ('public_website', 'Public website'), ('other', 'Other')], default='direct', max_length=16),
        ),
    ]
