# Generated by Django 5.1.15 on 2026-07-13 16:45

import apps.reservations.document_storage
import apps.reservations.document_validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_guest_father_name_guest_first_name_guest_last_name_and_more'),
        ('reservations', '0004_reservation_public_cancel_reason_and_more'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='primary_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='guests.guest'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='primary_guest_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='primary_guest_father_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='reservation',
            name='primary_guest_first_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='reservation',
            name='primary_guest_last_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='reservation',
            name='primary_guest_mother_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='reservation',
            name='primary_guest_national_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.CreateModel(
            name='ReservationOccupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=80)),
                ('last_name', models.CharField(blank=True, default='', max_length=80)),
                ('father_name', models.CharField(blank=True, default='', max_length=80)),
                ('mother_name', models.CharField(blank=True, default='', max_length=80)),
                ('national_id', models.CharField(blank=True, default='', max_length=80)),
                ('nationality', models.CharField(blank=True, default='', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, choices=[('spouse', 'Spouse'), ('child_adult', 'Adult child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('relative', 'Relative'), ('other', 'Other')], default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_occupancies', to='guests.guest')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_occupants', to='tenancy.hotel')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupants', to='reservations.reservation')),
            ],
            options={
                'db_table': 'reservation_occupants',
                'ordering': ['reservation_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReservationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(blank=True, choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('residence', 'Residence permit'), ('visa', 'Visa'), ('marriage_contract', 'Marriage contract'), ('family_book', 'Family book'), ('family_statement', 'Family statement'), ('other', 'Other')], default='', max_length=32)),
                ('number', models.CharField(blank=True, default='', max_length=64)),
                ('front_file', models.FileField(blank=True, null=True, storage=apps.reservations.document_storage.PrivateDocumentStorage(), upload_to=apps.reservations.document_storage.reservation_document_upload_to, validators=[apps.reservations.document_validators.validate_document_extension, apps.reservations.document_validators.validate_document_size, apps.reservations.document_validators.validate_document_signature])),
                ('back_file', models.FileField(blank=True, null=True, storage=apps.reservations.document_storage.PrivateDocumentStorage(), upload_to=apps.reservations.document_storage.reservation_document_upload_to, validators=[apps.reservations.document_validators.validate_document_extension, apps.reservations.document_validators.validate_document_size, apps.reservations.document_validators.validate_document_signature])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_documents', to='tenancy.hotel')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='reservations.reservation')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_documents_uploaded', to=settings.AUTH_USER_MODEL)),
                ('occupant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='reservations.reservationoccupant')),
            ],
            options={
                'db_table': 'reservation_documents',
                'ordering': ['reservation_id', 'id'],
            },
        ),
    ]
