# Generated by Django 5.1.15 on 2026-07-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_primary_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('held', 'Held'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('no_show', 'No-show')], default='confirmed', max_length=16),
        ),
        migrations.AlterField(
            model_name='reservationstatuslog',
            name='new_status',
            field=models.CharField(choices=[('held', 'Held'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('no_show', 'No-show')], max_length=16),
        ),
        migrations.AlterField(
            model_name='reservationstatuslog',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('held', 'Held'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('no_show', 'No-show')], default='', max_length=16),
        ),
    ]
