# Generated by Django 5.1.15 on 2026-07-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_reservation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationroomline',
            name='agreed_nightly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='reservationroomline',
            name='agreed_rate_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
