# Generated by Django 5.1.15 on 2026-07-16 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_reservationroomline_agreed_rate'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_number_sequence', to='tenancy.hotel')),
            ],
            options={
                'db_table': 'reservation_number_sequences',
            },
        ),
        migrations.CreateModel(
            name='ReservationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=32)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('consumed', 'Consumed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_drafts_created', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_drafts', to='tenancy.hotel')),
            ],
            options={
                'db_table': 'reservation_drafts',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'idempotency_key'), name='unique_reservation_draft_idempotency_key_per_hotel')],
            },
        ),
    ]
