# Generated by Django 5.1.15 on 2026-07-17 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_remove_guest_unique_guest_national_id_per_hotel_and_more'),
        ('reservations', '0008_reservationnumbersequence_reservationdraft'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='creation_idempotency_key',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='creation_request_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='reservationdraft',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_draft', to='reservations.reservation'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('creation_idempotency_key__isnull', False)), fields=('hotel', 'creation_idempotency_key'), name='unique_reservation_creation_idempotency_key_per_hotel'),
        ),
    ]
