# Generated by Django 5.1.15 on 2026-07-07 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("number", models.CharField(blank=True, default="", max_length=32)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floors",
                        to="tenancy.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "floors",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=32)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=140),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("dirty", "Dirty"),
                            ("cleaning", "Cleaning"),
                            ("maintenance", "Maintenance"),
                            ("out_of_service", "Out of service"),
                            ("archived", "Archived"),
                        ],
                        default="available",
                        max_length=16,
                    ),
                ),
                (
                    "status_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("status_changed_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rooms",
                        to="rooms.floor",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="tenancy.hotel",
                    ),
                ),
                (
                    "status_changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rooms",
                "ordering": ["floor__sort_order", "number"],
            },
        ),
        migrations.CreateModel(
            name="RoomStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("dirty", "Dirty"),
                            ("cleaning", "Cleaning"),
                            ("maintenance", "Maintenance"),
                            ("out_of_service", "Out of service"),
                            ("archived", "Archived"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("dirty", "Dirty"),
                            ("cleaning", "Cleaning"),
                            ("maintenance", "Maintenance"),
                            ("out_of_service", "Out of service"),
                            ("archived", "Archived"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_status_log_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_status_logs",
                        to="tenancy.hotel",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "db_table": "room_status_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("code", models.CharField(max_length=32)),
                ("description", models.TextField(blank=True, default="")),
                ("base_capacity", models.PositiveSmallIntegerField(default=1)),
                ("max_capacity", models.PositiveSmallIntegerField(default=1)),
                (
                    "bed_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("double", "Double"),
                            ("twin", "Twin"),
                            ("king", "King"),
                            ("queen", "Queen"),
                            ("suite", "Suite"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("amenities", models.JSONField(blank=True, default=list)),
                (
                    "base_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_types",
                        to="tenancy.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "room_types",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rooms",
                to="rooms.roomtype",
            ),
        ),
        migrations.AddConstraint(
            model_name="roomtype",
            constraint=models.UniqueConstraint(
                fields=("hotel", "code"), name="unique_room_type_code_per_hotel"
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("hotel", "number"), name="unique_room_number_per_hotel"
            ),
        ),
    ]
