# Generated by Django 5.1.15 on 2026-07-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='public_base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='public_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='public_is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='public_name',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='public_sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
