# Generated by Django 5.1.15 on 2026-07-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomtype_public_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='feature_additions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='room',
            name='feature_exclusions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
