# Generated by Django 5.1.15 on 2026-07-08 21:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_hotelmembership_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_number', models.CharField(max_length=20)),
                ('event_type', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('reservation', 'Reservation'), ('stay', 'Stay'), ('guest', 'Guest'), ('room', 'Room'), ('finance', 'Finance'), ('service', 'Service'), ('operation', 'Operation'), ('shift', 'Shift'), ('staff', 'Staff'), ('report', 'Report'), ('system', 'System')], default='system', max_length=16)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('related_object_type', models.CharField(blank=True, default='', max_length=64)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_url', models.CharField(blank=True, default='', max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events_acted', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='tenancy.hotel')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events_targeted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_events',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_number', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('reservation', 'Reservation'), ('stay', 'Stay'), ('guest', 'Guest'), ('room', 'Room'), ('finance', 'Finance'), ('service', 'Service'), ('operation', 'Operation'), ('shift', 'Shift'), ('staff', 'Staff'), ('report', 'Report'), ('system', 'System')], default='system', max_length=16)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('related_url', models.CharField(blank=True, default='', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.activityevent')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenancy.hotel')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hotel_notifications',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationsNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=16)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sequences', to='tenancy.hotel')),
            ],
            options={
                'db_table': 'notifications_number_sequences',
            },
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['hotel', 'category'], name='activity_ev_hotel_i_b1584c_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['hotel', 'occurred_at'], name='activity_ev_hotel_i_16190c_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityevent',
            constraint=models.UniqueConstraint(fields=('hotel', 'event_number'), name='unique_activity_event_number_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['hotel', 'recipient', 'is_read'], name='hotel_notif_hotel_i_1a3dac_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['hotel', 'recipient', 'is_archived'], name='hotel_notif_hotel_i_39824a_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('hotel', 'notification_number'), name='unique_notification_number_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='notificationsnumbersequence',
            constraint=models.UniqueConstraint(fields=('hotel', 'kind'), name='unique_notifications_sequence_per_hotel'),
        ),
    ]
