# Generated by Django 5.1.15 on 2026-07-11 13:35
# + hand-written SAFE backfill (restaurant/café final closure):
#   legacy `source`/`item_type` are KEPT (deprecated, read-only); their
#   meaning is copied into the new order_type/outlet columns. Nothing legacy
#   is deleted here — a separate cleanup migration comes later, after review.

from zoneinfo import ZoneInfo

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill(apps, schema_editor):
    ServiceOrder = apps.get_model("services", "ServiceOrder")
    ServiceCategory = apps.get_model("services", "ServiceCategory")
    ServiceItem = apps.get_model("services", "ServiceItem")

    # 1) Order shape from the deprecated `source`:
    #    a stay-bound order is a ROOM order; anything else is a legacy TABLE
    #    order without a table (read-only history). Outlet: cafe stays cafe,
    #    everything else (restaurant/room_service/other) maps to restaurant.
    ServiceOrder.objects.filter(stay__isnull=False).update(order_type="room")
    ServiceOrder.objects.filter(stay__isnull=True).update(order_type="table")
    ServiceOrder.objects.filter(source="cafe").update(outlet="cafe")
    ServiceOrder.objects.exclude(source="cafe").update(outlet="restaurant")

    # 2) Settlement state: a posted order was settled to the folio at its
    #    posting moment; everything else stays unsettled.
    ServiceOrder.objects.filter(posted_at__isnull=False).update(
        settlement="folio",
    )
    for order in ServiceOrder.objects.filter(posted_at__isnull=False).only(
        "id", "posted_at", "posted_by_id"
    ):
        ServiceOrder.objects.filter(pk=order.pk).update(
            settled_at=order.posted_at, settled_by_id=order.posted_by_id
        )

    # 3) business_date from ordered_at in the HOTEL's timezone (documented
    #    approximation for legacy rows — new rows are stamped by the service).
    tz_cache = {}
    for order in ServiceOrder.objects.select_related("hotel").only(
        "id", "ordered_at", "hotel_id"
    ):
        hotel_id = order.hotel_id
        if hotel_id not in tz_cache:
            HotelSettings = apps.get_model("hotels", "HotelSettings")
            row = HotelSettings.objects.filter(hotel_id=hotel_id).only("timezone").first()
            name = (row.timezone if row else "") or "UTC"
            try:
                tz_cache[hotel_id] = ZoneInfo(name)
            except (KeyError, ValueError):
                tz_cache[hotel_id] = ZoneInfo("UTC")
        local_date = order.ordered_at.astimezone(tz_cache[hotel_id]).date()
        ServiceOrder.objects.filter(pk=order.pk).update(business_date=local_date)

    # 4) Category outlet from the deprecated item_type: a category whose
    #    items are ALL café items becomes a café category; otherwise
    #    restaurant (the default).
    for category in ServiceCategory.objects.all().only("id"):
        types = set(
            ServiceItem.objects.filter(category_id=category.pk).values_list(
                "item_type", flat=True
            )
        )
        if types and types == {"cafe"}:
            ServiceCategory.objects.filter(pk=category.pk).update(outlet="cafe")


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_foliocharge_adjusts_payment_business_date_and_more'),
        ('hotels', '0004_hotelsettings_cafe_enabled_and_more'),
        ('rooms', '0002_roomtype_public_base_price_and_more'),
        ('services', '0001_initial'),
        ('stays', '0001_initial'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='outlet',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Café')], default='restaurant', max_length=16),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='business_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='order_type',
            field=models.CharField(choices=[('room', 'Room'), ('table', 'Table')], default='room', max_length=8),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='outlet',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Café')], default='restaurant', max_length=16),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders_settled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='settlement',
            field=models.CharField(choices=[('unsettled', 'Unsettled'), ('direct', 'Direct payment'), ('folio', 'Posted to folio')], default='unsettled', max_length=12),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='settlement_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settled_service_orders', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='serviceorderitem',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='serviceorderitem',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorderitem',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_order_items_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet', models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Café')], max_length=16)),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('available', 'Available'), ('out_of_service', 'Out of service')], default='available', max_length=16)),
                ('status_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_tables_created', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_tables', to='tenancy.hotel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_tables_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'restaurant_tables',
                'ordering': ['outlet', 'number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='services.restauranttable'),
        ),
        # Safe backfill BEFORE the index/constraints land: legacy meaning is
        # copied into the new columns; nothing is deleted (reverse = no-op).
        migrations.RunPython(_backfill, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['hotel', 'business_date'], name='svcorder_hotel_bizdate_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceorder',
            constraint=models.UniqueConstraint(condition=models.Q(('settled_at__isnull', True), ('table__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('table',), name='unique_open_order_per_table'),
        ),
        migrations.AddConstraint(
            model_name='serviceorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('settled_at__isnull', True), ('settlement', 'unsettled'), ('settlement_payment__isnull', True)), models.Q(('settled_at__isnull', False), ('settlement', 'direct'), ('settlement_payment__isnull', False)), models.Q(('posted_charge__isnull', False), ('settled_at__isnull', False), ('settlement', 'folio'), ('settlement_payment__isnull', True)), _connector='OR'), name='service_order_settlement_xor'),
        ),
        migrations.AddConstraint(
            model_name='restauranttable',
            constraint=models.UniqueConstraint(fields=('hotel', 'outlet', 'number'), name='unique_table_number_per_hotel_outlet'),
        ),
    ]
