# Generated by Django 5.1.15 on 2026-07-21 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_foliocharge_snapshots_and_wide_source'),
        ('rooms', '0003_room_feature_additions_room_feature_exclusions'),
        ('services', '0002_servicecategory_outlet_serviceorder_business_date_and_more'),
        ('stays', '0005_drop_stay_nightly_rate'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='amount_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='change_given',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='settlement_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='settlement_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='settlement_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='settlement_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='serviceorderitem',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='serviceorder',
            constraint=models.UniqueConstraint(condition=models.Q(('settlement_key', ''), _negated=True), fields=('hotel', 'settlement_key'), name='uniq_service_order_settlement_key'),
        ),
        migrations.AddConstraint(
            model_name='serviceorder',
            constraint=models.CheckConstraint(condition=models.Q(('settlement', 'direct'), models.Q(('amount_received__isnull', True), ('change_given__isnull', True)), _connector='OR'), name='service_order_cash_capture_direct_only'),
        ),
        migrations.AddConstraint(
            model_name='serviceorder',
            constraint=models.CheckConstraint(condition=models.Q(('amount_received__isnull', True), ('amount_received__gte', 0), _connector='OR'), name='service_order_amount_received_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='serviceorder',
            constraint=models.CheckConstraint(condition=models.Q(('change_given__isnull', True), ('change_given__gte', 0), _connector='OR'), name='service_order_change_non_negative'),
        ),
    ]
