# Generated by Django 5.1.15 on 2026-07-21 01:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_foliocharge_snapshots_and_wide_source'),
        ('services', '0003_serviceorder_amount_received_and_more'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=20)),
                ('kind', models.CharField(choices=[('return', 'Return'), ('exchange_same', 'Exchange (same price)'), ('exchange_higher', 'Exchange (higher price)'), ('exchange_lower', 'Exchange (lower price)')], default='return', max_length=16)),
                ('reason', models.CharField(max_length=255)),
                ('business_date', models.DateField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=64)),
                ('request_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_order_returns_created', to=settings.AUTH_USER_MODEL)),
                ('delta_charge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.foliocharge')),
                ('delta_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.payment')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_order_returns', to='tenancy.hotel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='services.serviceorder')),
                ('refund_folio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.folio')),
                ('refund_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.payment')),
                ('reversal_charge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.foliocharge')),
            ],
            options={
                'db_table': 'service_order_returns',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('item_name', models.CharField(max_length=160)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('replacement_name', models.CharField(blank=True, default='', max_length=160)),
                ('replacement_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('replacement_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('replacement_currency', models.CharField(blank=True, default='', max_length=3)),
                ('replacement_tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('replacement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('replacement_tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('replacement_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_order_return_items', to='tenancy.hotel')),
                ('original_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='services.serviceorderitem')),
                ('replacement_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_replacements', to='services.serviceitem')),
                ('service_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.serviceorderreturn')),
            ],
            options={
                'db_table': 'service_order_return_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='serviceorderreturn',
            constraint=models.UniqueConstraint(fields=('hotel', 'return_number'), name='uniq_service_order_return_number_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='serviceorderreturn',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('hotel', 'idempotency_key'), name='uniq_service_order_return_idempotency'),
        ),
    ]
