# Generated by Django 5.1.15 on 2026-07-21 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_foliocharge_snapshots_and_wide_source'),
        ('services', '0004_serviceorderreturn_serviceorderreturnitem_and_more'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderreturn',
            name='amount_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='serviceorderreturn',
            name='change_given',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='serviceorderreturn',
            constraint=models.CheckConstraint(condition=models.Q(('amount_received__isnull', True), ('amount_received__gte', 0), _connector='OR'), name='service_order_return_amount_received_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='serviceorderreturn',
            constraint=models.CheckConstraint(condition=models.Q(('change_given__isnull', True), ('change_given__gte', 0), _connector='OR'), name='service_order_return_change_non_negative'),
        ),
    ]
