# Generated by Django 5.1.15 on 2026-07-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_serviceorderreturn_amount_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='order_type',
            field=models.CharField(choices=[('room', 'Room'), ('table', 'Table'), ('direct', 'Direct customer')], default='room', max_length=8),
        ),
    ]
