# Generated by Django 5.1.15 on 2026-07-07 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('active', 'Active'), ('suspended', 'Suspended')], default='setup', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hotels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HotelMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary_manager', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hotel_users',
                'ordering': ['hotel_id', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'hotel'), name='unique_user_hotel_membership'), models.UniqueConstraint(condition=models.Q(('is_primary_manager', True)), fields=('hotel',), name='unique_primary_manager_per_hotel')],
            },
        ),
    ]
