# Generated by Django 5.1.15 on 2026-07-19 21:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0010_foliocharge_snapshots_and_wide_source'),
        ('stays', '0005_drop_stay_nightly_rate'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('name_normalized', models.CharField(default='', editable=False, max_length=180)),
                ('category', models.CharField(choices=[('laundry', 'Laundry'), ('parking', 'Parking'), ('transport', 'Transport'), ('minibar', 'Minibar'), ('extra_bed', 'Extra bed'), ('special_cleaning', 'Special cleaning'), ('damages', 'Damages'), ('external_request', 'External request'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('pricing_mode', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], default='fixed', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_extra_services_created', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_extra_services', to='tenancy.hotel')),
            ],
            options={
                'db_table': 'guest_extra_services',
                'ordering': ['display_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GuestServicePosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=64)),
                ('request_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_service_postings_created', to=settings.AUTH_USER_MODEL)),
                ('folio_charge', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.foliocharge')),
                ('guest_extra_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='guest_services.guestextraservice')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_service_postings', to='tenancy.hotel')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_service_postings', to='stays.stay')),
            ],
            options={
                'db_table': 'guest_service_postings',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='guestextraservice',
            constraint=models.UniqueConstraint(fields=('hotel', 'name_normalized'), name='uniq_guest_extra_service_name_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='guestextraservice',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='guest_extra_service_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='guestextraservice',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), name='guest_extra_service_tax_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='guestextraservice',
            constraint=models.CheckConstraint(condition=models.Q(('display_order__gte', 0)), name='guest_extra_service_display_order_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='guestextraservice',
            constraint=models.CheckConstraint(condition=models.Q(('name_normalized', ''), _negated=True), name='guest_extra_service_name_present'),
        ),
        migrations.AddConstraint(
            model_name='guestextraservice',
            constraint=models.CheckConstraint(condition=models.Q(('currency', ''), _negated=True), name='guest_extra_service_currency_present'),
        ),
        migrations.AddConstraint(
            model_name='guestserviceposting',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('hotel', 'idempotency_key'), name='uniq_guest_service_posting_idempotency'),
        ),
    ]
