# Generated by Django 5.1.15 on 2026-07-08 13:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('rooms', '0001_initial'),
        ('stays', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(max_length=20)),
                ('task_type', models.CharField(choices=[('checkout_cleaning', 'Check-out cleaning'), ('daily_cleaning', 'Daily cleaning'), ('deep_cleaning', 'Deep cleaning'), ('inspection', 'Inspection'), ('other', 'Other')], default='daily_cleaning', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=16)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('internal_notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_tasks_created', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='tenancy.hotel')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_tasks', to='rooms.room')),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_tasks', to='stays.stay')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_tasks_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'housekeeping_tasks',
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HousekeepingTaskStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, default='', max_length=16)),
                ('new_status', models.CharField(max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_status_changes', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_status_logs', to='tenancy.hotel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='operations.housekeepingtask')),
            ],
            options={
                'db_table': 'housekeeping_task_status_logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('documents', 'Documents'), ('clothing', 'Clothing'), ('jewelry', 'Jewelry'), ('money', 'Money'), ('luggage', 'Luggage'), ('other', 'Other')], default='other', max_length=16)),
                ('status', models.CharField(choices=[('found', 'Found'), ('stored', 'Stored'), ('claimed', 'Claimed'), ('returned', 'Returned'), ('disposed', 'Disposed'), ('closed', 'Closed')], default='found', max_length=16)),
                ('found_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('found_location', models.CharField(blank=True, default='', max_length=160)),
                ('stored_location', models.CharField(blank=True, default='', max_length=160)),
                ('claimed_by_name', models.CharField(blank=True, default='', max_length=180)),
                ('claimed_by_phone', models.CharField(blank=True, default='', max_length=32)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('disposed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('internal_notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_found_items_created', to=settings.AUTH_USER_MODEL)),
                ('found_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_found_items_found', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_found_items', to='guests.guest')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_found_items', to='tenancy.hotel')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_found_items', to='rooms.room')),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_found_items', to='stays.stay')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_found_items_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lost_found_items',
                'ordering': ['-found_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LostFoundItemStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, default='', max_length=16)),
                ('new_status', models.CharField(max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_found_status_changes', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_found_status_logs', to='tenancy.hotel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='operations.lostfounditem')),
            ],
            options={
                'db_table': 'lost_found_item_status_logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('hvac', 'HVAC'), ('furniture', 'Furniture'), ('cleaning_issue', 'Cleaning issue'), ('safety', 'Safety'), ('other', 'Other')], default='other', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('affects_room_availability', models.BooleanField(default=False)),
                ('room_block_status', models.CharField(choices=[('none', 'None'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of service')], default='none', max_length=16)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('internal_notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests_created', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='tenancy.hotel')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='rooms.room')),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='stays.stay')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maintenance_requests',
                'ordering': ['-reported_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequestStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, default='', max_length=16)),
                ('new_status', models.CharField(max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_status_changes', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_status_logs', to='tenancy.hotel')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='operations.maintenancerequest')),
            ],
            options={
                'db_table': 'maintenance_request_status_logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OperationsNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=16)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_sequences', to='tenancy.hotel')),
            ],
            options={
                'db_table': 'operations_number_sequences',
            },
        ),
        migrations.AddIndex(
            model_name='housekeepingtask',
            index=models.Index(fields=['hotel', 'status'], name='housekeepin_hotel_i_48b76e_idx'),
        ),
        migrations.AddIndex(
            model_name='housekeepingtask',
            index=models.Index(fields=['hotel', 'requested_at'], name='housekeepin_hotel_i_1bbcb9_idx'),
        ),
        migrations.AddConstraint(
            model_name='housekeepingtask',
            constraint=models.UniqueConstraint(fields=('hotel', 'task_number'), name='unique_housekeeping_task_number_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='lostfounditem',
            index=models.Index(fields=['hotel', 'status'], name='lost_found__hotel_i_67b60a_idx'),
        ),
        migrations.AddIndex(
            model_name='lostfounditem',
            index=models.Index(fields=['hotel', 'found_at'], name='lost_found__hotel_i_1c3e89_idx'),
        ),
        migrations.AddConstraint(
            model_name='lostfounditem',
            constraint=models.UniqueConstraint(fields=('hotel', 'item_number'), name='unique_lost_found_item_number_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['hotel', 'status'], name='maintenance_hotel_i_e3c18d_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['hotel', 'reported_at'], name='maintenance_hotel_i_28ab25_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerequest',
            constraint=models.UniqueConstraint(fields=('hotel', 'request_number'), name='unique_maintenance_request_number_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='operationsnumbersequence',
            constraint=models.UniqueConstraint(fields=('hotel', 'kind'), name='unique_operations_sequence_per_hotel'),
        ),
    ]
