# Generated by Django 5.1.15 on 2026-07-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekeepingtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('awaiting_inspection', 'Awaiting inspection'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='housekeepingtaskstatuslog',
            name='new_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='housekeepingtaskstatuslog',
            name='previous_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
