# Generated by Django 5.1.15 on 2026-07-18 23:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_housekeepingtask_status_and_more'),
        ('rooms', '0003_room_feature_additions_room_feature_exclusions'),
        ('stays', '0005_drop_stay_nightly_rate'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='housekeepingtask',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'assigned', 'in_progress', 'awaiting_inspection']), ('room__isnull', False)), fields=('hotel', 'room'), name='uniq_active_housekeeping_task_per_room'),
        ),
    ]
