# Generated by Django 5.1.15 on 2026-07-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_add_active_housekeeping_task_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeepingtask',
            name='service_outcome',
            field=models.CharField(blank=True, choices=[('cleaned', 'Cleaned'), ('guest_refused', 'Guest refused'), ('do_not_disturb', 'Do not disturb'), ('no_access', 'No access')], default='', max_length=20),
        ),
    ]
