# Generated by Django 5.1.15 on 2026-07-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_housekeepingtask_service_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfounditem',
            name='claim_proof_reference',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='lostfounditem',
            name='claim_proof_type',
            field=models.CharField(blank=True, choices=[('identity_last4', 'Identity document — last 4'), ('receipt_reference', 'Receipt / reference number'), ('ownership_description', 'Ownership description'), ('other', 'Other')], default='', max_length=24),
        ),
    ]
