# Generated by Django 5.1.4 on 2026-07-19 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0008_alter_guestblocklog_guest_protect'),
        ('operations', '0005_lostfounditem_claim_proof_reference_and_more'),
        ('reservations', '0009_reservation_creation_idempotency_key_and_more'),
        ('stays', '0005_drop_stay_nightly_rate'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('documents', 'Documents'), ('clothing', 'Clothing'), ('jewelry', 'Jewelry'), ('money', 'Money'), ('luggage', 'Luggage'), ('other', 'Other')], default='other', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('distinctive_marks', models.CharField(blank=True, default='', max_length=255)),
                ('last_seen_location', models.CharField(blank=True, default='', max_length=160)),
                ('lost_at', models.DateTimeField(blank=True, null=True)),
                ('reporter_name', models.CharField(blank=True, default='', max_length=180)),
                ('reporter_phone', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('searching', 'Searching'), ('matched', 'Matched'), ('returned', 'Returned'), ('closed_unfound', 'Closed (not found)'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('internal_notes', models.CharField(blank=True, default='', max_length=255)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('unfound_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_reports_created', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_reports', to='guests.guest')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_reports', to='tenancy.hotel')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_reports_matched', to=settings.AUTH_USER_MODEL)),
                ('matched_found_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_by_reports', to='operations.lostfounditem')),
                ('reported_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_reports_reported', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_reports', to='reservations.reservation')),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_reports', to='stays.stay')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_reports_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lost_reports',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LostReportStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_report_status_changes', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_report_status_logs', to='tenancy.hotel')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='operations.lostreport')),
            ],
            options={
                'db_table': 'lost_report_status_logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='lostreport',
            index=models.Index(fields=['hotel', 'status'], name='lost_report_hotel_i_4b0d5d_idx'),
        ),
        migrations.AddIndex(
            model_name='lostreport',
            index=models.Index(fields=['hotel', 'created_at'], name='lost_report_hotel_i_43291d_idx'),
        ),
        migrations.AddConstraint(
            model_name='lostreport',
            constraint=models.UniqueConstraint(fields=('hotel', 'report_number'), name='unique_lost_report_number_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='lostreport',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'matched'), ('matched_found_item__isnull', False)), fields=('matched_found_item',), name='uniq_matched_found_item_active_report'),
        ),
    ]
