# Generated by Django 5.1.15 on 2026-07-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform_name", models.CharField(default="Funduqii", max_length=140)),
                (
                    "support_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "support_phone",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "support_whatsapp",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("website_url", models.URLField(blank=True, default="")),
                (
                    "default_language",
                    models.CharField(
                        choices=[
                            ("ar", "Arabic"),
                            ("en", "English"),
                            ("tr", "Turkish"),
                        ],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("default_currency", models.CharField(default="USD", max_length=3)),
                ("default_trial_days", models.PositiveIntegerField(default=14)),
                ("allow_public_registration", models.BooleanField(default=False)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform settings",
                "verbose_name_plural": "Platform settings",
                "db_table": "platform_settings",
            },
        ),
    ]
