# Generated by Django 5.1.15 on 2026-07-09 00:07

import apps.platform.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPublicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_home_link', models.BooleanField(default=True)),
                ('show_hotels_link', models.BooleanField(default=True)),
                ('show_contact_link', models.BooleanField(default=True)),
                ('show_book_now_button', models.BooleanField(default=True)),
                ('show_trial_button', models.BooleanField(default=True)),
                ('header_home_label', models.JSONField(blank=True, default=apps.platform.models._blank_i18n)),
                ('header_hotels_label', models.JSONField(blank=True, default=apps.platform.models._blank_i18n)),
                ('header_contact_label', models.JSONField(blank=True, default=apps.platform.models._blank_i18n)),
                ('header_book_now_label', models.JSONField(blank=True, default=apps.platform.models._blank_i18n)),
                ('header_trial_label', models.JSONField(blank=True, default=apps.platform.models._blank_i18n)),
                ('hero_title', models.JSONField(blank=True, default=apps.platform.models._blank_i18n)),
                ('hero_subtitle', models.JSONField(blank=True, default=apps.platform.models._blank_i18n)),
                ('hero_primary_button_label', models.JSONField(blank=True, default=apps.platform.models._blank_i18n)),
                ('hero_primary_button_url', models.CharField(blank=True, default='', max_length=300)),
                ('hero_secondary_button_label', models.JSONField(blank=True, default=apps.platform.models._blank_i18n)),
                ('hero_secondary_button_url', models.CharField(blank=True, default='', max_length=300)),
                ('public_phone', models.CharField(blank=True, default='', max_length=32)),
                ('public_whatsapp_display', models.CharField(blank=True, default='', max_length=32)),
                ('public_email', models.EmailField(blank=True, default='', max_length=254)),
                ('public_address', models.CharField(blank=True, default='', max_length=255)),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('website_url', models.URLField(blank=True, default='')),
                ('footer_text', models.JSONField(blank=True, default=apps.platform.models._blank_i18n)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform public settings',
                'verbose_name_plural': 'Platform public settings',
                'db_table': 'platform_public_settings',
            },
        ),
    ]
