# Generated by Django 5.1.15 on 2026-07-08 15:29

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_hotelmembership_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_number', models.CharField(max_length=20)),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='draft', max_length=16)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('snapshot_json', models.JSONField(blank=True, default=dict)),
                ('totals_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_closes_closed', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_closes', to='tenancy.hotel')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_closes_reopened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_closes',
                'ordering': ['-business_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DailyCloseStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, default='', max_length=16)),
                ('new_status', models.CharField(max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_close_status_changes', to=settings.AUTH_USER_MODEL)),
                ('daily_close', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='shifts.dailyclose')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_close_status_logs', to='tenancy.hotel')),
            ],
            options={
                'db_table': 'daily_close_status_logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_number', models.CharField(max_length=20)),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closing', 'Closing'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('opening_cash_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expected_cash_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('actual_cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('difference_reason', models.CharField(blank=True, default='', max_length=255)),
                ('opening_notes', models.CharField(blank=True, default='', max_length=255)),
                ('closing_notes', models.CharField(blank=True, default='', max_length=255)),
                ('internal_notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_created', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='tenancy.hotel')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_opened', to=settings.AUTH_USER_MODEL)),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts_responsible', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shifts',
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handover_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('summary_notes', models.CharField(blank=True, default='', max_length=255)),
                ('pending_tasks_notes', models.CharField(blank=True, default='', max_length=255)),
                ('cash_notes', models.CharField(blank=True, default='', max_length=255)),
                ('guest_notes', models.CharField(blank=True, default='', max_length=255)),
                ('maintenance_notes', models.CharField(blank=True, default='', max_length=255)),
                ('lost_found_notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_created', to=settings.AUTH_USER_MODEL)),
                ('from_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers', to='shifts.shift')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_handovers', to='tenancy.hotel')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers_received', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shift_handovers',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShiftHandoverStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, default='', max_length=16)),
                ('new_status', models.CharField(max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_status_changes', to=settings.AUTH_USER_MODEL)),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='shifts.shifthandover')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_status_logs', to='tenancy.hotel')),
            ],
            options={
                'db_table': 'shift_handover_status_logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShiftsNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=16)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts_sequences', to='tenancy.hotel')),
            ],
            options={
                'db_table': 'shifts_number_sequences',
            },
        ),
        migrations.CreateModel(
            name='ShiftStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, default='', max_length=16)),
                ('new_status', models.CharField(max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_status_changes', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_status_logs', to='tenancy.hotel')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='shifts.shift')),
            ],
            options={
                'db_table': 'shift_status_logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyclose',
            constraint=models.UniqueConstraint(fields=('hotel', 'business_date'), name='unique_daily_close_per_hotel_date'),
        ),
        migrations.AddConstraint(
            model_name='dailyclose',
            constraint=models.UniqueConstraint(fields=('hotel', 'close_number'), name='unique_daily_close_number_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['hotel', 'status'], name='shifts_hotel_i_fbe2dc_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['hotel', 'business_date'], name='shifts_hotel_i_dcd8ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('hotel', 'shift_number'), name='unique_shift_number_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('hotel', 'responsible_user'), name='unique_open_shift_per_user_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='shifthandover',
            index=models.Index(fields=['hotel', 'status'], name='shift_hando_hotel_i_c68283_idx'),
        ),
        migrations.AddConstraint(
            model_name='shifthandover',
            constraint=models.UniqueConstraint(fields=('hotel', 'handover_number'), name='unique_handover_number_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='shiftsnumbersequence',
            constraint=models.UniqueConstraint(fields=('hotel', 'kind'), name='unique_shifts_sequence_per_hotel'),
        ),
    ]
