# Generated by Django 5.1.15 on 2026-07-11 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_expense_shift_payment_shift'),
        ('guests', '0002_guest_block_reason_guest_blocked_at_guest_blocked_by_and_more'),
        ('reservations', '0004_reservation_public_cancel_reason_and_more'),
        ('shifts', '0001_initial'),
        ('stays', '0001_initial'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foliocharge',
            name='adjusts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='finance.foliocharge'),
        ),
        migrations.AddField(
            model_name='payment',
            name='business_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='finance.payment'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['hotel', 'business_date'], name='pay_hotel_bizdate_idx'),
        ),
        migrations.AddConstraint(
            model_name='folio',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open'), ('stay__isnull', False)), fields=('stay',), name='unique_open_folio_per_stay'),
        ),
        migrations.AddConstraint(
            model_name='foliocharge',
            constraint=models.UniqueConstraint(condition=models.Q(('adjusts__isnull', False), ('status', 'posted')), fields=('adjusts',), name='unique_posted_adjustment_per_charge'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('reverses__isnull', False), ('status', 'posted')), fields=('reverses',), name='unique_posted_reversal_per_payment'),
        ),
    ]
