# Generated by Django 5.1.15 on 2026-07-11 16:11
# + hand-written SAFE backfill (expenses final closure): legacy vouchers get
#   their business_date derived from paid_at in the HOTEL timezone. Nothing
#   is deleted or overwritten beyond the new NULL column (reverse = no-op).

from zoneinfo import ZoneInfo

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill(apps, schema_editor):
    Expense = apps.get_model("finance", "Expense")
    HotelSettings = apps.get_model("hotels", "HotelSettings")

    tz_cache = {}
    for expense in Expense.objects.filter(business_date__isnull=True).only(
        "id", "paid_at", "hotel_id"
    ):
        hotel_id = expense.hotel_id
        if hotel_id not in tz_cache:
            row = HotelSettings.objects.filter(hotel_id=hotel_id).only("timezone").first()
            name = (row.timezone if row else "") or "UTC"
            try:
                tz_cache[hotel_id] = ZoneInfo(name)
            except (KeyError, ValueError):
                tz_cache[hotel_id] = ZoneInfo("UTC")
        local_date = expense.paid_at.astimezone(tz_cache[hotel_id]).date()
        Expense.objects.filter(pk=expense.pk).update(business_date=local_date)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_foliocharge_adjusts_payment_business_date_and_more'),
        ('hotels', '0004_hotelsettings_cafe_enabled_and_more'),
        ('shifts', '0001_initial'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='business_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='finance.expense'),
        ),
        # Safe backfill BEFORE the index/constraints land (reverse = no-op).
        migrations.RunPython(_backfill, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['hotel', 'business_date'], name='exp_hotel_bizdate_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('reverses__isnull', False), ('status', 'posted')), fields=('reverses',), name='unique_posted_reversal_per_expense'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('reverses__isnull', False), ('amount__gt', 0), _connector='OR'), name='expense_amount_sign'),
        ),
    ]
