# Generated by Django 5.1.15 on 2026-07-13 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_expense_business_date_expense_reverses_and_more'),
        ('guests', '0002_guest_block_reason_guest_blocked_at_guest_blocked_by_and_more'),
        ('reservations', '0004_reservation_public_cancel_reason_and_more'),
        ('stays', '0001_initial'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='rate_basis',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='rate_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='rate_entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_rates_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank transfer'), ('electronic', 'Electronic'), ('internal_electronic', 'Internal electronic'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank transfer'), ('electronic', 'Electronic'), ('internal_electronic', 'Internal electronic'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='folio',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open'), ('stay__isnull', True)), fields=('reservation',), name='unique_open_folio_per_reservation'),
        ),
    ]
