# Generated by Django 5.1.15 on 2026-07-14 22:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_payment_exchange_rate_payment_original_amount_and_more'),
        ('reservations', '0006_alter_reservation_status_and_more'),
        ('stays', '0001_initial'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='awaiting_final_charges',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folio',
            name='awaiting_final_charges_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='RefundableInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deducted_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('held', 'Held'), ('refunded', 'Refunded'), ('partially_deducted', 'Partially deducted'), ('consumed', 'Consumed')], default='held', max_length=20)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank transfer'), ('electronic', 'Electronic'), ('internal_electronic', 'Internal electronic'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('received_at', models.DateTimeField()),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurances_created', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='tenancy.hotel')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurances_received', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurances', to='reservations.reservation')),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurances_settled', to=settings.AUTH_USER_MODEL)),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurances', to='stays.stay')),
            ],
            options={
                'db_table': 'refundable_insurances',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['hotel', 'status'], name='insurance_hotel_status_idx'), models.Index(fields=['stay'], name='insurance_stay_idx'), models.Index(fields=['reservation'], name='insurance_reservation_idx')],
            },
        ),
    ]
