# Generated by Django 5.1.15 on 2026-07-15 09:14

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_folio_awaiting_final_charges_and_more'),
        ('reservations', '0006_alter_reservation_status_and_more'),
        ('stays', '0001_initial'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='refundableinsurance',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='insurance_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='refundableinsurance',
            constraint=models.CheckConstraint(condition=models.Q(('deducted_amount__gte', 0)), name='insurance_deducted_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='refundableinsurance',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_amount__gte', 0)), name='insurance_refunded_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='refundableinsurance',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', django.db.models.expressions.CombinedExpression(models.F('deducted_amount'), '+', models.F('refunded_amount')))), name='insurance_settled_within_amount'),
        ),
        migrations.AddConstraint(
            model_name='refundableinsurance',
            constraint=models.CheckConstraint(condition=models.Q(('currency', ''), _negated=True), name='insurance_currency_present'),
        ),
    ]
