# Generated by Django 5.1.15 on 2026-07-15 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_refundableinsurance_insurance_amount_positive_and_more'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foliocharge',
            name='room_night',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='foliocharge',
            constraint=models.UniqueConstraint(condition=models.Q(('room_night__isnull', False), ('status', 'posted')), fields=('folio', 'room_night'), name='uniq_posted_room_night_per_folio'),
        ),
    ]
