# Generated by Django 5.1.15 on 2026-07-19 20:19
#
# GUEST-FOLIO-EXTRA-SERVICES-CLOSURE / P2 + PKG-CONST.
#   * Adds five NULLABLE frozen-snapshot columns to FolioCharge (currency,
#     service name, unit price, tax rate, source reference). Additive, no
#     backfill, no FK to any catalog — a later rename/reprice can never mutate a
#     posted charge's snapshot. Existing rows stay NULL and valid.
#   * Widens ``source`` from varchar(16) to varchar(32) so the canonical
#     ``ChargeSource`` values fit — ``guest_extra_service`` is 19 chars and would
#     not fit the old 16. The column TYPE is unchanged (still CharField/varchar);
#     only its length grew. Widening a varchar is a metadata-only, non-rewriting,
#     reversible operation on PostgreSQL; no stored value changes.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_foliocharge_room_night_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foliocharge',
            name='currency_snapshot',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='foliocharge',
            name='service_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foliocharge',
            name='source_reference',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='foliocharge',
            name='tax_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='foliocharge',
            name='unit_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='foliocharge',
            name='source',
            field=models.CharField(blank=True, default='manual', max_length=32),
        ),
    ]
