# Generated by Django 5.1.15 on 2026-07-21 21:39

import apps.finance.expense_storage
import apps.finance.expense_validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_foliocharge_snapshots_and_wide_source'),
        ('shifts', '0001_initial'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=apps.finance.expense_storage.PrivateExpenseStorage(), upload_to=apps.finance.expense_storage.expense_attachment_upload_to, validators=[apps.finance.expense_validators.validate_attachment_extension, apps.finance.expense_validators.validate_attachment_size, apps.finance.expense_validators.validate_attachment_signature]),
        ),
        migrations.AddField(
            model_name='expense',
            name='creation_idempotency_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='expense',
            name='creation_request_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='expense',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='original_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='expense',
            name='rate_basis',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='expense',
            name='rate_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='rate_entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_rates_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, choices=[('operations', 'Operations'), ('maintenance', 'Maintenance'), ('supplies', 'Supplies'), ('marketing', 'Marketing'), ('salary', 'Salary'), ('utilities', 'Utilities'), ('other', 'Other')], default='other', max_length=16),
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('name_normalized', models.CharField(editable=False, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_types_created', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_types', to='tenancy.hotel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_types_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expense_types',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensetype'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('creation_idempotency_key', ''), _negated=True), fields=('hotel', 'creation_idempotency_key'), name='unique_expense_creation_idempotency_key_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='expensetype',
            constraint=models.UniqueConstraint(fields=('hotel', 'name_normalized'), name='unique_expense_type_name_per_hotel'),
        ),
    ]
