# Generated by Django 5.1.15 on 2026-07-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionplan_is_public_and_more'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hotelsubscription',
            index=models.Index(fields=['hotel', 'status'], name='hotel_subsc_hotel_i_6f5968_idx'),
        ),
    ]
