# Generated by Django 5.1.15 on 2026-07-17 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_hotelsubscription_plan_snapshot'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('new_subscription', 'New subscription'), ('renewal', 'Renewal'), ('plan_change', 'Plan change')], max_length=20)),
                ('status', models.CharField(choices=[('under_review', 'Under review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('executed', 'Executed')], default='under_review', max_length=16)),
                ('hotel_note', models.TextField(blank=True, default='')),
                ('admin_note', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='subscriptions.hotelsubscription')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='tenancy.hotel')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_requests_made', to=settings.AUTH_USER_MODEL)),
                ('requested_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='subscriptions.subscriptionplan')),
                ('resulting_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='subscriptions.hotelsubscription')),
            ],
            options={
                'db_table': 'subscription_change_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hotel', 'status'], name='subscriptio_hotel_i_58ac51_idx'), models.Index(fields=['status'], name='subscriptio_status_b3d73d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['under_review', 'accepted'])), fields=('hotel',), name='unique_open_request_per_hotel')],
            },
        ),
    ]
