# Generated by Django 5.1.15 on 2026-07-13 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_guest_block_reason_guest_blocked_at_guest_blocked_by_and_more'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='guest',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='guest',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='guest',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='guest',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='guest',
            name='national_id_normalized',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='guest',
            name='no_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='phone_normalized',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='guest',
            constraint=models.UniqueConstraint(condition=models.Q(('national_id', ''), _negated=True), fields=('hotel', 'national_id'), name='unique_guest_national_id_per_hotel'),
        ),
    ]
