# Generated by Django 5.1.15 on 2026-07-13 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_guest_father_name_guest_first_name_guest_last_name_and_more'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guest',
            name='unique_guest_national_id_per_hotel',
        ),
        migrations.AddConstraint(
            model_name='guest',
            constraint=models.UniqueConstraint(condition=models.Q(('national_id_normalized', ''), _negated=True), fields=('hotel', 'national_id_normalized'), name='unique_guest_national_id_per_hotel'),
        ),
    ]
