# Generated by Django 5.1.15 on 2026-07-07 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='tenancy.hotelmembership')),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['membership_id', 'code'],
                'constraints': [models.UniqueConstraint(fields=('membership', 'code'), name='unique_membership_permission')],
            },
        ),
    ]
