# Generated by Django 5.1.15 on 2026-07-07 15:10

import apps.hotels.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "legal_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "short_description",
                    models.CharField(blank=True, default="", max_length=280),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "star_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "default_language",
                    models.CharField(
                        choices=[
                            ("ar", "Arabic"),
                            ("en", "English"),
                            ("tr", "Turkish"),
                        ],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("default_currency", models.CharField(default="USD", max_length=3)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                (
                    "whatsapp_number",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("website_url", models.URLField(blank=True, default="")),
                ("facebook_url", models.URLField(blank=True, default="")),
                ("instagram_url", models.URLField(blank=True, default="")),
                ("social_links", models.JSONField(blank=True, default=dict)),
                ("country", models.CharField(blank=True, default="", max_length=80)),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                ("area", models.CharField(blank=True, default="", max_length=120)),
                (
                    "address_line",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("map_url", models.URLField(blank=True, default="")),
                (
                    "google_place_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "location_notes",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                ("cancellation_policy", models.TextField(blank=True, default="")),
                ("child_policy", models.TextField(blank=True, default="")),
                (
                    "pet_policy",
                    models.CharField(
                        choices=[
                            ("not_allowed", "Not allowed"),
                            ("allowed", "Allowed"),
                            ("on_request", "On request"),
                        ],
                        default="not_allowed",
                        max_length=16,
                    ),
                ),
                (
                    "smoking_policy",
                    models.CharField(
                        choices=[
                            ("not_allowed", "Not allowed"),
                            ("allowed", "Allowed"),
                            ("designated", "Designated areas"),
                        ],
                        default="not_allowed",
                        max_length=16,
                    ),
                ),
                ("extra_bed_policy", models.TextField(blank=True, default="")),
                ("important_notes", models.TextField(blank=True, default="")),
                (
                    "default_booking_status",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("allow_public_booking", models.BooleanField(default=False)),
                ("require_guest_phone", models.BooleanField(default=True)),
                ("require_guest_document", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hotel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="tenancy.hotel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel settings",
                "verbose_name_plural": "Hotel settings",
                "db_table": "hotel_settings",
            },
        ),
        migrations.CreateModel(
            name="HotelMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("logo", "Logo"),
                            ("cover", "Cover"),
                            ("gallery", "Gallery"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.hotels.models.hotel_media_upload_to
                    ),
                ),
                ("alt_text", models.CharField(blank=True, default="", max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="tenancy.hotel",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_hotel_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hotel_media",
                "ordering": ["kind", "sort_order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True), ("kind", "logo")),
                        fields=("hotel",),
                        name="unique_active_logo_per_hotel",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True), ("kind", "cover")),
                        fields=("hotel",),
                        name="unique_active_cover_per_hotel",
                    ),
                ],
            },
        ),
    ]
