# Generated by Django 5.1.15 on 2026-07-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='public_booking_requires_confirmation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='public_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='public_is_listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='public_max_nights',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='public_min_nights',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='public_sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='public_terms_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
