# Generated by Django 5.1.15 on 2026-07-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotelsettings_public_booking_requires_confirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='housekeeping_inspection_required',
            field=models.BooleanField(default=False),
        ),
    ]
