# Generated by Django 5.1.15 on 2026-07-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotelsettings_housekeeping_inspection_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='cafe_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='restaurant_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
