# Generated by Django 5.1.15 on 2026-07-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotelsettings_business_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='accepted_currencies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
