# Generated by Django 5.1.15 on 2026-07-17 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_hotelsettings_accepted_currencies'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='facility_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('apartments', 'Apartments'), ('resort', 'Resort'), ('motel', 'Motel'), ('guesthouse', 'Guest house'), ('other', 'Other')], default='hotel', max_length=20),
        ),
        migrations.CreateModel(
            name='SettingsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('hotel', 'Hotel'), ('platform', 'Platform')], default='hotel', max_length=16)),
                ('section', models.CharField(max_length=40)),
                ('changes', models.JSONField(default=dict)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_changes', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings_audit_logs', to='tenancy.hotel')),
            ],
            options={
                'db_table': 'settings_audit_logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['hotel', '-created_at'], name='settings_au_hotel_i_ac6624_idx'), models.Index(fields=['scope', '-created_at'], name='settings_au_scope_1e56ee_idx')],
            },
        ),
    ]
