# Generated by Django 5.1.15 on 2026-07-17 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_hotelsettings_facility_type_settingsauditlog'),
        ('tenancy', '0003_hotel_status_changed_at_hotel_status_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='settingsauditlog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hotel__isnull', False), ('scope', 'hotel')), models.Q(('hotel__isnull', True), ('scope', 'platform')), _connector='OR'), name='settings_audit_scope_hotel_consistency'),
        ),
    ]
